[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs']

[phases.install]
cmds = ['cd backend && composer install --no-dev --no-scripts --optimize-autoloader']

[start]
cmd = 'cd backend && php artisan serve --host=0.0.0.0 --port=$PORT'
